# Generated by Django 4.2.3 on 2023-08-01 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MovieReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("headline", models.TextField(blank=True, null=True)),
                ("summary", models.TextField(blank=True, null=True)),
                ("publication_date", models.DateField(blank=True, null=True)),
                ("link", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="reviews/images", verbose_name="image"
                    ),
                ),
            ],
        ),
    ]
