# Generated by Django 4.2.3 on 2023-07-25 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('headline', models.TextField()),
                ('summary', models.TextField()),
                ('publication_date', models.DateField()),
                ('link', models.CharField(max_length=200)),
                ('image_url', models.CharField(max_length=200)),
                ('image_height', models.IntegerField()),
                ('image_width', models.IntegerField()),
            ],
        ),
    ]
