# Generated by Django 4.2.3 on 2023-07-30 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviereview',
            name='headline',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moviereview',
            name='image_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moviereview',
            name='image_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='moviereview',
            name='image_width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moviereview',
            name='link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='moviereview',
            name='publication_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moviereview',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
